=== gaurbprajapati/public_api_automation/src/test/resources/publicApi/invoice/getAllInvoicesAPI.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Get all invoices API response",
	"type": "object",
	"properties": {
		"current_page": {
			"type": "integer"
		},
		"data": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "integer"
					},
					"company_slug": {
						"type": "string"
					},
					"status_id": {
						"type": "integer"
					},
					"created_on": {
						"type": "string"
					},
					"updated_on": {
						"type": "string"
					}
				}
			}
		},
		"first_page_url": {
			"type": "string"
		},
		"from": {
			"type": "integer"
		},
		"next_page_url": {},
		"path": {
			"type": "string"
		},
		"per_page": {},
		"prev_page_url": {},
		"to": {
			"type": "integer"
		}
	},
	"required": [
		"current_page",
		"data",
		"first_page_url",
		"from",
		"next_page_url",
		"path",
		"per_page",
		"prev_page_url",
		"to"
	],
	"additionalProperties": true
}

=== gaurbprajapati/public_api_automation/src/test/resources/publicApi/calllog/getAllCalllogs.json
{
    "current_page": 1,
    "data": [
        {
            "id": 7202146,
            "call_type": "CALL_INCOMING",
            "custom_call_type": null,
            "call_started_on": "2023-05-22T18:45:00.000000Z",
            "contact_number": "1-029-842-9485",
            "call_notes": "Call log Description - People are different. People choose different criteria. But if there is a better way among many alternatives, I want to encourage that way by making it comfortable. So that's what I've tried to do.<br><br>Tenetur et harum voluptates vel necessitatibus.",
            "related_to": "16854191416730196015Wam",
            "related_to_type": "candidate",
            "created_on": "2023-05-22T18:45:00.000000Z",
            "updated_on": "2023-05-30T03:59:05.000000Z",
            "created_by": 196015,
            "updated_by": 196015,
            "related": {
                "id": 14,
                "first_name": "Rosena Candidate",
                "last_name": "Gaylord",
                "email": "rcrmtest0@gmail.com",
                "contact_number": "1-549-573-5777",
                "gender_id": 1,
                "qualification_id": 1,
                "specialization": "Technical savvy",
                "work_ex_year": 23,
                "candidate_dob": "2014-03-19T15:24:55.000000Z",
                "current_salary": 809352,
                "salary_expectation": 3752252,
                "resume": {
                    "filename": "sandeep_resume.pdf",
                    "file_link": "https://neo-mrapi.recruitcrm.net/v1/candidates/16854191416730196015Wam/resume/eyJpdiI6IkZTSE5kNXhlNnJVZ0E0cUxLU3N1dGc9PSIsInZhbHVlIjoiU0FoaW55cGZ2bWM3NHArYWNnSzR6LzFnSGpYa2J3TmVaMVRDZEpvOGZzSFJKK0JJZEo2dy9oQWNmQS9JVDA3U3hDQmlvREppUEJuNklkSXhrNE9wd08wMUdmbUlVZmxkdWxMS21HRzRxYzQ9IiwibWFjIjoiMzUwYjI3NDMzMzQxZjQ1MjFmNjk2NjA3NTcxZTg4NTY4YmFiZThlOGU0YjFlMjI5ZWUzZWIzNTkwM2Q0YjBmNSJ9"
                },
                "willing_to_relocate": 1,
                "current_organization": "Nolan, Halvorson and Feeney",
                "current_status": "Glomerulonephritis",
                "notice_period": 920,
                "currency_id": 76,
                "slug": "16854191416730196015Wam",
                "profile_update_link_status": 0,
                "profile_update_requested_on": null,
                "profile_updated_on": null,
                "avatar": "https://neo-mrapi.recruitcrm.net/v1/candidates/16854191416730196015Wam/avatar/eyJpdiI6Ik9pVkJJejBjK2lBVFB5UHJjT1NuNkE9PSIsInZhbHVlIjoiTkRrRHIzc3VzbzRCdHl0bkNFYXFKZz09IiwibWFjIjoiYTlhMmQ2NDRmZWIwNmRlMmVjYjg3MTA4YWQzMDQ0ZDNjZWM3MzdkMzk3ZWRmZDhhZGQ0ZTE3OWRiNzlkNjJhMSJ9",
                "facebook": "https://www.sherrie-aufderhar.org",
                "twitter": "https://www.pamila-pagac.co",
                "linkedin": "https://www.ada-upton.name",
                "github": "https://www.kristofer-schumm.biz",
                "xing": "https://www.demetrius-monahan.name",
                "created_on": "2023-05-30T03:59:01.000000Z",
                "updated_on": "2023-05-30T03:59:05.000000Z",
                "city": "Vergiestad",
                "locality": "48329 Mattie Drive",
                "address": "Apt. 756 2683 Jeromy Roads, Myronmouth, IL 58015-2083",
                "relevant_experience": 9,
                "position": "Dynamic Security Strategist",
                "available_from": "2023-05-30T16:45:06.000000Z",
                "salary_type": {
                    "id": "5",
                    "label": "Hourly Salary"
                },
                "source": "Default Value",
                "language_skills": null,
                "skill": "Fast learner,Proactive,Fast learner,",
                "custom_fields": [],
                "created_by": {
                    "id": 196015,
                    "first_name": "Account99439677753",
                    "last_name": "1",
                    "email": "dev.Owner_1685418267429@yopmail.com",
                    "contact_number": null,
                    "avatar": null
                },
                "updated_by": {
                    "id": 196015,
                    "first_name": "Account99439677753",
                    "last_name": "1",
                    "email": "dev.Owner_1685418267429@yopmail.com",
                    "contact_number": null,
                    "avatar": null
                },
                "owner": {
                    "id": 196015,
                    "first_name": "Account99439677753",
                    "last_name": "1",
                    "email": "dev.Owner_1685418267429@yopmail.com",
                    "contact_number": null,
                    "avatar": null
                },
                "resource_url": "https://neo-mr.recruitcrm.net/candidate/16854191416730196015Wam",
                "qualification": {
                    "qualification_id": 1,
                    "label": "High School Dropout"
                },
                "currency": {
                    "currency_id": 76,
                    "code": "EUR",
                    "country": "Malta",
                    "currency": "Euro",
                    "symbol": "€"
                }
            },
            "associated_candidates": [
                "16854191416730196015Wam"
            ],
            "associated_contacts": [],
            "associated_companies": [],
            "associated_jobs": [],
            "associated_deals": []
        }
    ],
    "first_page_url": "https://neo-mrapi.recruitcrm.net/v1/call-logs?limit=1&page=1&page=1",
    "from": 1,
    "next_page_url": null,
    "path": "https://neo-mrapi.recruitcrm.net/v1/call-logs?limit=1&page=1",
    "per_page": "1",
    "prev_page_url": null,
    "to": 1
}
